---
all:
  children:
    linux:
      hosts:
        web01:
          ansible_host: 192.0.2.10
        backup01:
          ansible_host: 192.0.2.20
    windows:
      hosts:
        winserver01:
          ansible_host: 192.0.2.30

